sudo: required
before_script:
- sudo add-apt-repository -y ppa:ceph-ubuntu/edgers
- sudo apt-get update -q
- sudo apt-get install librbd-dev
- pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
language: rust
script:
- |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo --only stable doc
after_success:
- travis-cargo --only stable doc-upload
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - secure: bpSFA28J+SER27RxiNc/D7HtS39gF7y8KBxdoJDhEPI2EcDvSMlnh7PIINZEwPG7NR9EnrKSA3nkDrGLdppPZ27mytL39jDfPao/b0opO96atDczlbJAMBPJGPjrV+z1oXCceljAaZlN+JCflpoP6sJdZvpf0ktQzNGto1rDKkGOsNyxxN5XjDHY6Z/6Iws9ukofUpadSIJGufN72+94BE/eEqPqK1PbK3psdSnUzw3viK5tMINBZtorI0OrfI9UXDfIiS/vevH49m4ot7rPVrwcUKFuhjJh4rfCvdOUub+mUINp1mj/3JR9kH+TTKU2J8LyBHVPaN4QttHrPi7NZVioVwl+Cn61VVb2OjBWAdXq855jPaInSZtXafKdR5htx0Rw9jtYLLstcnzwX9VeUvAOs81U4eIahppFRci+j+DdtQhARI8JyFwgqC6pjKX6zgn4BZdsjPGt+FsN9YCbtY/NLIBabN3DAp8jIwuEyss2CjZP4MeU/KKH5MAIslQFKgAIRUekEBVbyQ1X1P2V8Ijo0i0gyuFrpybp2Um4Md1++q9Ap7PUM2aaVQre3VcXAK19skwEDa3HLdrgo5Xeov7RtsXqygq4153gAGuCoLu9xjvdHR0Xyne4BULkqZp7M9YhN4yDrNZ/wpIA5JosUWEnfNGU4Zxd4Ddorl//nUE=
cache:
  apt: true
  rust-download: true
  directories:
  - "~/.cargo"
notifications:
  email:
    on_success: never
